--- 
apiVersion: cert-manager.io/v1
kind: Certificate
metadata: 
  name: plex-cert
spec: 
  acme: 
    config: 
      - dns01: 
          provider: cloudflare
        domains: 
          - plex.mymarshall5.com
  dnsNames: 
    - plex.mymarshall5.com
  issuerRef: 
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: plex-mymarshall5-com
