---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex-cert
spec:
  secretName: plex-mymarshall5-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "plex.mymarshall5.com"
  acme:
    config:
    - dns01:
        provider: cloudflare
      domains:
      - "plex.mymarshall5.com"