--- 
apiVersion: cert-manager.io/v1
kind: Certificate
metadata: 
  name: plex-cert
spec: 
  dnsNames: 
  - plex.mymarshall5.com
  issuerRef: 
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: plex-mymarshall5-com
