---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: haproxy-project
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: haproxy Project
  sourceRepos:
    - "*"
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haproxy
  namespace: argocd
spec:
  project: haproxy-project
  destination:
    server: https://kubernetes.default.svc
    namespace: haproxy
  source:
    chart: haproxy
    repoURL: https://haproxytech.github.io/helm-charts
    targetRevision: 1.6.0
    helm:
      values: |
        service:
          type: LoadBalancer
          loadBalancerIP: "192.168.1.180"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
