apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/pool-ui.yaml
  - resources/pool-ui-configmap.yaml
images:
- name: n8marshall/nodejs-poolcontroller-dashpanel
  newTag: 1668365624
namespace: pool
