apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/pool-ui.yaml
  - resources/pool-ui-configmap.yaml
images:
  - name: msmi/nodejs-poolcontroller-dashpanel
    #newTag: "10MAR2303"
    newTag: "latest"
namespace: pool
