apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/pool-ui.yaml
  - resources/pool-ui-configmap.yaml
images:
  # - name: n8marshall/nodejs-poolcontroller-dashpanel
    # newTag: "7439736423"
  - name: msmi/nodejs-poolcontroller-dashpanel
    # newTag: "latest"
    # newTag: "8.0.0"
    newTag: "7.6.1"
namespace: pool
