apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/pool-ui.yaml
  - resources/pool-ui-configmap.yaml
images:
  # - name: n8marshall/nodejs-poolcontroller-dashpanel
  #   newTag: "6785403990"
  - name: msmi/nodejs-poolcontroller-dashpanel
  #   newTag: "latest"
    newTag: "8.0.0"
namespace: pool
