---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr-deployment
  namespace: media
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          imagePullPolicy: Always
          image: linuxserver/radarr
          ports:
            - containerPort: 7878
          volumeMounts:
            - mountPath: /config
              name: radarr-config
            - mountPath: /nfs/media/movies
              name: nfs-movies
            - mountPath: /nfs/media/familymovies
              name: nfs-familymovies
            - mountPath: /nfs/media/christmas
              name: nfs-christmas
            - mountPath: /nfs/downloads
              name: nfs-downloads
      volumes:
        - name: nfs-movies
          nfs:
            server: x.x.x.249
            path: /media/nate/MediaFiles/media/movies
        - name: nfs-familymovies
          nfs:
            server: x.x.x.249
            path: /media/nate/MediaFiles/media/familymovies
        - name: nfs-christmas
          nfs:
            server: x.x.x.249
            path: /media/nate/MediaFiles/media/christmas
        - name: nfs-downloads
          nfs:
            server: x.x.x.249
            path: /media/nate/MediaFiles/downloads
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: radarr-service
  namespace: media
spec:
  loadBalancerIP: x.x.x.178
  ports:
    - protocol: TCP
      name: "7878"
      port: 7878
  selector:
    app: radarr
  type: LoadBalancer
  externalTrafficPolicy: Local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-pvc
  namespace: media
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: raspberrypi-3
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
