apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grocy-database
  namespace: grocy
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: raspberrypi-2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi