apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: uptime-kuma
  name: uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      service: uptime-kuma
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: uptime-kuma
    spec:
      containers:
        - image: louislam/uptime-kuma:1
          name: uptime-kuma
          ports:
            - containerPort: 3001
          resources: {}
          volumeMounts:
            - mountPath: /app/data
              name: uptime-kuma-pvc
      restartPolicy: Always
      volumes:
        - name: uptime-kuma-pvc
          persistentVolumeClaim:
            claimName: uptime-kuma-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-pvc
  namespace: monitoring
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    path: k3s-node-21/
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1000Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: uptime-kuma
  name: uptime-kuma
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
  selector:
    service: uptime-kuma
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.1.183
---
