apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
spec:
  nodeSelector:
    kubernetes.io/hostname: raspberrypi-2
  containers:
    - name: dnsutils
      image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
