---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr-deployment
  namespace: media
  labels:
    app: overseerr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overseerr
  template:
    metadata:
      labels:
        app: overseerr
    spec:
      containers:
        - name: overseerr
#          command: ["tail", "-f", "/dev/null"]
          imagePullPolicy: Always
          image: 'linuxserver/overseerr:develop'
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - '-c'
                - cat /mediafiles/healthy.txt
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 64Mi
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: TZ
              value: "America/Chicago"
          ports:
            - containerPort: 5055
          volumeMounts:
            - mountPath: /app/config
              name: overseerr-config
            - mountPath: /mediafiles
              name: media-volume
      dnsConfig:
        nameservers:
          - 1.1.1.1
      volumes:
        - name: media-volume
          nfs:
            path: /media/nate/Media12TB
            server: 192.168.1.60
        - name: overseerr-config
          persistentVolumeClaim:
            claimName: overseerr-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: overseerr-service
  namespace: media
spec:
  loadBalancerIP: 192.168.1.185
  ports:
    - protocol: TCP
      name: "5055"
      port: 5055
  selector:
    app: overseerr
  type: LoadBalancer
  externalTrafficPolicy: Local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-config-pvc
  namespace: media
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: raspberrypi-3
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
