apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.1.1
  - https://github.com/argoproj-labs/argocd-notifications/manifests/controller
  - resources/argocd-configmap.yaml
  - resources/argocd-rbac-cm.yaml
  - resources/argocd-repo-server.yaml