apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.2.3
  # - https://github.com/argoproj/argo-cd/manifests/cluster-install
  - https://github.com/argoproj-labs/argocd-notifications/manifests/controller
  - resources/argocd-ingress.yaml
  - ../../argocd-proj-apps

patchesStrategicMerge:
  - resources/argocd-application-controller.yaml
  - resources/argocd-dex-server.yaml
  - resources/argocd-repo-server.yaml
  - resources/argocd-rbac-cm.yaml
  - resources/argocd-server.yaml
  - resources/argocd-configmap.yaml

namespace: argocd
