apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: quay.io/argoproj/argocd
    newTag: v2.7.7
resources:
  - https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.10.1
  # - resources/argocd-ingress.yaml
  - ../../argocd-proj-apps
  - resources/cmp-plugin.yaml
  # Descheduler
  #- github.com/kubernetes-sigs/descheduler/kubernetes/deployment?ref=v0.26.0
  #- resources/descheduler-policy.yaml

patchesStrategicMerge:
  - resources/argocd-repo-server.yaml
  - resources/argocd-rbac-cm.yaml
  - resources/argocd-server.yaml
  - resources/argocd-configmap.yaml

namespace: argocd
