---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd-deployment
  namespace: media
  labels:
    app: sabnzbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - raspberrypi-2
      containers:
        - name: sabnzbd
          image: linuxserver/sabnzbd
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
            - containerPort: 9090
          volumeMounts:
            - mountPath: /config
              name: sabnzbd-config
            - mountPath: /tempdownload
              name: sabdnzbd-tempdownload
            - mountPath: /nfs
              name: nfs-volume
      volumes:
        - name: nfs-volume
          nfs:
            server: 192.168.1.99
            path: /f/media
        - name: sabnzbd-config
          persistentVolumeClaim:
            claimName: sabnzbd-config-pvc
        - name: sabdnzbd-tempdownload
          persistentVolumeClaim:
            claimName: sabnzbd-tempdownload-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd-service
  namespace: media
spec:
  ports:
    - protocol: TCP
      name: "8080"
      port: 8080
    - protocol: TCP
      name: "9090"
      port: 9090
  selector:
    app: sabnzbd
  type: LoadBalancer
  externalTrafficPolicy: Local