---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: handbrake-tv-deployment
  namespace: media
  labels:
    app: handbrake-tv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: handbrake-tv
  template:
    metadata:
      labels:
        app: handbrake-tv
    spec:
      containers:
        - name: handbrake-tv
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Chicago"
            - name: KEEP_APP_RUNNING
              value: "1"
            - name: CLEAN_TMP_DIR
              value: "1"
            - name: AUTOMATED_CONVERSION_PRESET
              value: "Custom/720p30v2"
            - name: AUTOMATED_CONVERSION_KEEP_SOURCE
              value: "0"
            - name: AUTOMATED_CONVERSION_FORMAT
              value: "mp4"
            - name: AUTOMATED_CONVERSION_SOURCE_STABLE_TIME
              value: "90"
            - name: AUTOMATED_CONVERSION_OUTPUT_DIR
              value: "/nfs/downloads/tmp/tv"
            - name: AUTOMATED_CONVERSION_OUTPUT_SUBDIR
              value: "SAME_AS_SRC"
            - name: AUTOMATED_CONVERSION_OVERWRITE_OUTPUT
              value: "1"
          resources:
            requests:
              cpu: 1000m
              memory: 1024Mi
            limits:
              cpu: 3000m
              memory: 1000Mi
          image: jlesage/handbrake
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - cat /nfs/downloads/healthy.txt && cat /nfs/media/tv/healthy.txt
          ports:
            - containerPort: 5800
          volumeMounts:
            - mountPath: /config
              name: handbrake-tv-config
            - mountPath: /nfs/media/tv
              name: nfs-tv
            - mountPath: /nfs/downloads
              name: nfs-downloads
      dnsConfig:
        nameservers:
          - 1.1.1.1
      volumes:
        - name: nfs-tv
          nfs:
            server: 192.168.1.60
            path:  /media/14TB_00/media/tv
        - name: nfs-downloads
          nfs:
            server: 192.168.1.60
            path: /media/nate/Media12TB/media_downloads
        - name: handbrake-tv-config
          persistentVolumeClaim:
            claimName: handbrake-tv-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: handbrake-tv-service
  namespace: media
spec:
  loadBalancerIP: 192.168.1.192
  ports:
    - protocol: TCP
      name: "5800"
      port: 5800
  selector:
    app: handbrake-tv
  type: LoadBalancer
  externalTrafficPolicy: Local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: handbrake-tv-config-pvc
  namespace: media
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: media-ubuntu
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
