apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/cockroachdb/cockroach-operator/v2.9.0/install/crds.yaml
  - https://raw.githubusercontent.com/cockroachdb/cockroach-operator/v2.9.0/install/operator.yaml
  - resources/deployment.yaml