apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: pod-ralm
      protocol: layer2
      addresses:
      - 192.168.1.175-192.168.1.199
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: m5-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.175-192.168.1.199