---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchpotato-deployment
  namespace: media
  labels:
    app: couchpotato
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchpotato
  template:
    metadata:
      labels:
        app: couchpotato
    spec:
      containers:
        - name: couchpotato
#          command: ["tail", "-f", "/dev/null"]
          image: linuxserver/couchpotato
          ports:
            - containerPort: 5050
          volumeMounts:
            - mountPath: /config
              name: couchpotato-config
            - mountPath: /nfs
              name: nfs-volume
      volumes:
        - name: nfs-volume
          nfs:
            server: x.x.x.13
            path: /f/media
        - name: couchpotato-config
          persistentVolumeClaim:
            claimName: couchpotato-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: couchpotato-service
  namespace: media
spec:
  ports:
    - protocol: TCP
      name: "5050"
      port: 5050
  selector:
    app: couchpotato
  type: LoadBalancer
  externalTrafficPolicy: Local
