---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall-deployment
  namespace: media
  labels:
    app: heimdall
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      containers:
        - name: heimdall
          image: linuxserver/heimdall:arm32v7-latest
          ports:
            - containerPort: 8080
#            - containerPort: 443
          volumeMounts:
            - mountPath: /config
              name: heimdall-config
          env:
            - name: PUID
              value: "998"
            - name: PGID
              value: "1002"
            - name: TZ
              value: "America/Chicago"
          resources:
            requests:
              memory: 50Mi
              cpu: 50m
            limits:
              memory: 100Mi
              cpu: 100m
          imagePullPolicy: Always
      volumes:
        - name: heimdall-config
          persistentVolumeClaim:
            claimName: heimdall-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: heimdall-service
  namespace: media
spec:
  ports:
    - protocol: TCP
      name: "8080"
      port: 8080
#    - protocol: TCP
#      name: "443"
#      port: 443
  selector:
    app: heimdall
  type: LoadBalancer
  externalTrafficPolicy: Local