---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr-deployment
  namespace: media
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
#          command: ["tail", "-f", "/dev/null"]
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - cat /media/nate/BlueIris/media_downloads/downloads/healthy.txt && cat /nfs/media/series/healthy.txt && cat /nfs/media/familytv/healthy.txt
            initialDelaySeconds: 5
            periodSeconds: 30
          imagePullPolicy: Always
          image: linuxserver/sonarr
          resources:
            limits:
              cpu: 500m
              memory: 750Mi
          ports:
            - containerPort: 8989
          volumeMounts:
            - mountPath: /config
              name: sonarr-config
            - mountPath: /nfs/media/familytv
              name: nfs-familytv
            - mountPath: /media/nate/BlueIris/media_downloads
              name: nfs-downloads
      dnsConfig:
        nameservers:
          - 1.1.1.1
      volumes:
        - name: nfs-familytv
          nfs:
            server: 192.168.1.60
            path: /media/nate/MediaFiles/media/familytv
        - name: nfs-downloads
          nfs:
            server: 192.168.1.60
            path: /media/nate/MediaFiles/downloads
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: sonar-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr-service
  namespace: media
spec:
  loadBalancerIP: 192.168.1.189
  ports:
    - protocol: TCP
      name: "8989"
      port: 8989
  selector:
    app: sonarr
  type: LoadBalancer
  externalTrafficPolicy: Local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-config-pvc
  namespace: media
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: raspberrypi-2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
