---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cert-manager-project
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: cert-manager Project
  sourceRepos:
    - "*"
  destinations:
    - namespace: '*'
      server: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: cert-manager-project
  source:
    helm:
      parameters:
        - name: app
          value: $ARGOCD_APP_NAME
        - name: installCRDs
          value: "true"
    chart: jetstack/cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.5.3
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
