---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kube-system-project
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: kube-system Project
  sourceRepos:
  - '*'
  destinations:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-system
  namespace: argocd
spec:
  project: kube-system-project
  source:
    repoURL: https://github.com/nate-marshall/rpi-media-cluster.git
    targetRevision: master
    path: manifests/kube-system
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    # syncOptions:
    #   - CreateNamespace=true