---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: media-project
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Media Project
  sourceRepos:
    - "*"
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media
  namespace: argocd
spec:
  project: media-project
  source:
    repoURL: https://github.com/nate-marshall/rpi-media-cluster.git
    targetRevision: master
    path: manifests/media
  plugin:
    name: argocd-vault-plugin
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
