---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: metallb-project
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: metallb Project
  sourceRepos:
    - "*"
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: metallb-project
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  source:
    repoURL: https://github.com/nate-marshall/rpi-media-cluster.git
    targetRevision: master
    path: manifests/metallb
  syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
    syncOptions:
      - CreateNamespace=true
