---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: metallb-project
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: metallb Project
  sourceRepos:
    - "*"
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: metallb-project
  source:
    chart: metallb/metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.10.2
    helm:
      parameters:
        - name: app
          value: $ARGOCD_APP_NAME
      values: |
        configInline:
          address-pools:
          - name: default
          protocol: layer2
          addresses:
          - 192.168.1.175-192.168.1.199
