---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prometheus-project
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: prometheus Project
  sourceRepos:
    - "*"
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: prometheus-project
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  source:
    chart: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 19.3.0
    helm:
      values: |
        pushgateway:
          enabled: false
        server:
          service:
            type: LoadBalancer
            loadBalancerIP: "192.168.1.198"
    plugin:
      name: argocd-vault-plugin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
