---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: signoz-project
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: SigNoz Project
  sourceRepos:
    - "*"
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  namespace: argocd
spec:
  project: signoz-project
  source:
    chart: signoz
    repoURL: https://charts.signoz.io
    targetRevision: 0.7.1
    helm:
      releaseName: signoz
  destination:
    server: "https://kubernetes.default.svc"
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true