apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  # Example of argocd-cm -- https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
  admin.enabled: "true"
  url: https://argocd.mymarshall5.com
  configManagementPlugins: |
    - name: argocd-vault-plugin-kustomize
      generate:
        command: ["sh", "-c"]
        args: ["kustomize build . > all.yaml && argocd-vault-plugin generate all.yaml"]
