#cat <<EOF | kubectl apply -n argocd -f -
apiVersion: v1
stringData:
  # Will be renamed to ARGOCD_ENV_AVP_AUTH_TYPE by ArgoCD before reaching the plugin.
  AVP_AUTH_TYPE: vault
kind: Secret
metadata:
  name: vault-configuration
  namespace: argocd
type: Opaque
#EOF