cat <<EOF | kubectl apply -n argocd -f -
apiVersion: v1
stringData:
  VAULT_ADDR: https://192.168.1.196
  VAULT_TOKEN: mysecrettoken
  AVP_TYPE: vault
  AVP_AUTH_TYPE: token
kind: Secret
metadata:
  name: vault-configuration
  namespace: argocd
type: Opaque
EOF

---
cat <<EOF | kubectl apply -n argocd -f -
apiVersion: v1
stringData:
  VAULT_ADDR: https://192.168.1.196
  VAULT_TOKEN: mysecrettoken
  AVP_TYPE: vault
  AVP_AUTH_TYPE: token
kind: Secret
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
EOF
