name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [15.x, 16.x]

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: "14.x"
    - uses: actions/checkout@v2
    - name: Build the Pool UI Docker Image
      run: |
       VERSION=$(date +%s)
       wget -q https://github.com/rstrouse/nodejs-poolController-dashPanel/archive/refs/heads/master.zip
       unzip -qq master
       cd nodejs-poolController-dashPanel-master
       echo "${{ secrets.DOCKERHUB_PASS }}" | docker login -u n8marshall --password-stdin
       docker build . --file Dockerfile --tag n8marshall/nodejs-poolcontroller-dashpanel:${VERSION}
       docker push n8marshall/nodejs-poolcontroller-dashpanel:${VERSION}
