name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Pool UI Docker image
      run: docker build . --file manifests/pool-ui/Dockerfile --tag nodejs-poolcontroller-dashpanel:$(date +%s)
