name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Pool UI Docker Image
      run: |
       VERSION=$(date +%s)
       wget https://github.com/rstrouse/nodejs-poolController-dashPanel/archive/refs/heads/master.zip
       unzip master
       cd nodejs-poolController-dashPanel-master
       env|sort
       docker login -u n8marshall -p ${{ secrets.DOCKERHUB_PASS }}
       docker build . --file Dockerfile --tag n8marshall/nodejs-poolcontroller-dashpanel:${VERSION}
       docker push n8marshall/nodejs-poolcontroller-dashpanel:${VERSION}
